name: Build & publish

on:
  push:
    branches:
      - main
      - git_integration
      - template_integration
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login into ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        run: |
          export GITHUB_RUN_ID=${{ github.run_id }}
          echo ${DOCKER_CONFIG}
          cd server-ce/
          make build-base
          make build-community

      - name: List Docker images
        run: docker images

      - name: Set image tag based on branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
      
          if [ "$BRANCH_NAME" = "main" ]; then
            TAG="latest"
          elif [ "$BRANCH_NAME" = "git_integration" ]; then
            TAG="git"
          else
            CLEAN_BRANCH=$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9]/-/g')
            TAG=$CLEAN_BRANCH
          fi
      
          echo "TAG=$TAG" >> $GITHUB_ENV
  

      - name: Publish
        run: |
          set -e
      
          ghcr_registry="ghcr.io/theelse2098/overleaf-artishow"
      
          echo "Using TAG=$TAG"
      
          docker images
      
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          CLEAN_BRANCH=$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9]/_/g')
      
          SOURCE_IMAGE="sharelatex/sharelatex:${CLEAN_BRANCH}"
      
          echo "Using SOURCE_IMAGE=$SOURCE_IMAGE"
      
          docker tag $SOURCE_IMAGE ${ghcr_registry}:${TAG}
          docker tag $SOURCE_IMAGE ${ghcr_registry}:${{ github.sha }}
      
          docker push ${ghcr_registry}:${TAG}
